app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-54-78-36-245.eu-west-1.compute.amazonaws.com:5432/d9cd584jkdmbna
    username: heurjlinjcgwbc
    password: 3c441beac58be30d0e883f8e7f505432dbcb49b2beb5ddd49956a871a812da68
    pool-size: 30

server.error.include-message: always