app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-52-213-119-221.eu-west-1.compute.amazonaws.com:5432/ddhd7o2bsfaiuq
    username: nhjzcqyiwjzjqj
    password: ea37f5e1a8b11703f2765ed42b2ed629c1a0e9693b837dd17cb21f9823d8e466
    pool-size: 30

  jwt:
    secretKey: TpbMDT7fN9ABn491KaxntJcmtpEOR1YZA9fwW6tf1ljpiC0TDlh0yw
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 5